### PR TITLE
adding detectOutsideBlock (default = true) flag. By setting it to false ...

### PR DESCRIPTION
**Pull request by kether667**
...wiredep will look only at dependencies within the block and ignore contents of the file. As a result all dependencies will be injected into block.

resolves taptapship/wiredep#108

let me know what you think, this is just a preliminary checkin, will add unit tests and then we can megre

### CODE REVIEW

**Comment by kether667** [comment]
Hi can we merge this in please? or is there anything particular you'd like me to address ?

**Comment by kether667** [comment]
Hi can we do something about this PR?

**Comment by stephenplusplus** [comment]
Yeah, we should. I'm really sorry to let it stand for so long. I think what we want to end up with for this PR is removing "excludes" on the file type level, and just remove the autodetection functionality that wiredep currently has altogether. Once that's in, we can release 3.0.0 and call this one done. Thank you so much for doing all of this for us.

> we already have override in bower.json that can be used to exclude file what would be the use cases where we want to have additional exclude at wiredep level?

Well at this point, it's because we already have it :) And we have it to give users a useful programmatic API, since `overrides` isn't a standard Bower property.

**Comment by stephenplusplus** [comment]
Took care of this in master. Thanks!

**Pull request closed without merging**
