### PR TITLE
Updated to latest npm dependencies. (using latest version of lodash)

### PR DESCRIPTION
**Pull request by igorlino**
(chai is back :) )

### CODE REVIEW

**Comment by stephenplusplus** [comment]
One of the upgrades broke the tests :( https://travis-ci.org/taptapship/wiredep/builds/66594646

If you have a chance to take a look at what happened, that would be great. If not, I'm happy to look into it,  it just will take me some time to get around to it.

Thanks again for helping out!

**Comment by igorlino** [comment]
Ah yes. How can I reproduce the CI build, I tried locally to build but somehow I'm missing some dev env setup.

1) npm install
2) npm test

**Comment by stephenplusplus** [comment]
That should be the only process you need to go through. `npm install` and `npm test`. What happened when you tried to run the tests?

**Comment by igorlino** [comment]
First it complains jshint is not there. So then I used "npm install -g jshint"
IO
Then it complains about NODE_ENV:

C:\projects\wiredep>npm test

> wiredep@2.2.2 test C:\projects\wiredep
> jshint *.js lib/*.js test/*.js && NODE_ENV=test mocha -R spec

ERROR: Can't open *.js
ERROR: Can't open lib/*.js
ERROR: Can't open test/*.js
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.

**Comment by igorlino** [comment]
I have the feeling that the tests only work under Linux.  but as I only have windows, I cannot tell.
Do you run the tests under Linux or OSX,or do you use Windows?

**Comment by eddiemonge** [comment]
One of the dependencies is breaking the tests. Here is the expected:

```
  %link{href:\'../bower_components/codecode/dist/codecode.css\', rel:\'stylesheet\'}
  %link{href:\'../bower_components/bootstrap/dist/css/bootstrap.css\', rel:\'stylesheet\'}
    %script{type:\'text/javascript\', src:\'../bower_components/jquery/jquery.js\'}
    %script{type:\'text/javascript\', src:\'../bower_components/codecode/dist/codecode.js\'}
    %script{type:\'text/javascript\', src:\'../bower_components/bootstrap/dist/js/bootstrap.js\'}
```

and the actual:

```
  %link{rel:\'stylesheet\', href:\'../bower_components/codecode/dist/codecode.css\'}
  %link{rel:\'stylesheet\', href:\'../bower_components/bootstrap/dist/css/bootstrap.css\'}
    %script{src:\'../bower_components/jquery/jquery.js\'}
    %script{src:\'../bower_components/codecode/dist/codecode.js\'}
    %script{src:\'../bower_components/bootstrap/dist/js/bootstrap.js\'}
```

The href and rel got reversed for links and type got dropped for scripts. So maybe tests just need to be updated but this could be considered a breaking change

**Comment by eddiemonge** [comment]
lodash upgrade is breaking the tests. Since that isn't urgent to upgrade, closing this. Might look into removing it entirely.

Thanks for the work in this though

**Pull request closed without merging**
